# NOTE!!! if can not be compile, maybe an extra 
# space ' ' is behind the name.
# NAME  = shared_ptr_vector
# NAME  = shared_ptr2
# NAME  = shared_ptr
# SRC   = src/language/cpp/

NAME  = mocker1
SRC   = src/os/

BUILD = build/
OBJ = $(BUILD)$(SRC)$(NAME)

CPP = $(SRC)$(NAME).cpp

# CXX = g++
CXX = nvcc
# CXXFLAGS = -std=c++98 -Wall -Wextra -g
# CXXFLAGS = -Wall -Wextra -g -std=c++20
CXXFLAGS = -lcublas

# CPP = $(SRC)$(NAME).c

# $(error $(OBJ))
# $(error $(CPP))

run:
	@mkdir -p $(BUILD)$(SRC)
	@$(CXX) $(CXXFLAGS) -o $(OBJ) $(CPP)
# $(CXX) $(CXXFLAGS) -o $(OBJ) $(CPP)
	@$(OBJ)

clean:
	rm -rf $(BUILD)
